This repository contains my solutions for the exercises of Structure
and Interpretation of Computer Programs by Abelson.

* How to Find Solution for A Certain Exercise

To find the solution of a certain exercise, search for the number of
the exercise, for example "Exercise 4.21". Solution for some certain
exercises are scattered, thus I feel it is not proper to put the
number of such exercises at a certain place. For such an exercise,
search the exercise number in the commit log, I will make sure it
appears there.

Please note that solutions are scattered among multiple branches,
since I find it difficult to maintain them all in a single
branch. This is because some of the exercises are based on different
foundations, for example, some are based on analyzing evaluator while
the others are based on normal order evaluator.

I will try to put the most of the solutions in the main/master branch,
and name the other branches so it should be obvious what it is
about. Anyway, if you fail to find certain solution in one branch, try
search the others.
